operators:
  - name: group-sync-operator
    metadata:
      operatorName: group-sync-operator
      namespace: group-sync-operator
    subscription: 
      channel: alpha
      name: group-sync-operator
      source: community-operators
      sourceNamespace: openshift-marketplace
    operatorGroupNamespaces: 
      - group-sync-operator
    createNamespace: true

  - name: argocd
    metadata:
      operatorName: argocd-operator
      namespace: argocd
    subscription: 
      channel: alpha
      name: argocd-operator
      source: community-operators
      sourceNamespace: openshift-marketplace
    operatorGroupNamespaces: 
      - argocd
    createNamespace: false

  - name: container-security-operator
    metadata:
      operatorName: container-security-operator
      namespace: openshift-operators
    subscription: 
      channel: quay-v3.3
      installPlanApproval: Automatic
      name: container-security-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorGroupNamespaces: 
      - openshift-operators
    createNamespace: false