custom_logo_name: cyan-hat-openshift-container-platform.png
instances:
  - namespace: openshift-config
    configMapName: cyan-hat-console-custom-logo
  # - namespace: openshift-console
  #   configMapName: custom-logo