{{- range $operators := .Values.operators }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $operators.metadata.operatorName }}
  namespace: {{ $operators.metadata.namespace }}
spec:
  {{- range $key, $val := $operators.subscription }}
  {{ $key }}: {{ $val }}
  {{- end }}
{{- end }}