{{- range $operators := .Values.operators }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ $operators.metadata.operatorName }}
  namespace: {{ $operators.metadata.namespace }}
spec:
  targetNamespaces:
  {{- range $operators.operatorGroupNamespaces }}
  - {{ . }}
  {{- end }}
{{- end }}