git_repo_url: https://github.com/AJ1701/argocd-apps
git_repo_branch: main

applications:
  - metadata:
      name: authentication
      argocdNamespace: argocd
    helm:
      valueFiles:
        - crc-values.yaml
    selfHeal: true
    prune: true
  - metadata:
      name: cluster-admins
      argocdNamespace: argocd
    helm:
      valueFiles:
        - crc-values.yaml
    selfHeal: true
    prune: true
  - metadata:
      name: cyan-hat
      argocdNamespace: argocd
    helm:
      valueFiles:
        - crc-values.yaml
    selfHeal: true
    prune: true
  - metadata:
      name: hello-world
      argocdNamespace: argocd
    selfHeal: true
    prune: true
  - metadata:
      name: new-relic
      argocdNamespace: argocd
    helm:
      valueFiles:
        - crc-values.yaml
    selfHeal: true
    prune: true
  - metadata:
      name: operators
      argocdNamespace: argocd
    helm:
      valueFiles:
        - crc-values.yaml
    # selfHeal: true
    # prune: true
