apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AJ1701/argocd-demo-dev
    targetRevision: main
    path: hello-world
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world #Destination of the apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true