operators:

  - name: argocd
    metadata:
      operatorName: argocd-operator
      namespace: argocd
    subscription: 
      channel: alpha
      installPlanApproval: Automatic
      name: argocd-operator
      source: community-operators
      sourceNamespace: openshift-marketplace
    operatorGroupNamespaces: 
      - argocd
    createNamespace: false

  - name: container-security-operator
    metadata:
      operatorName: container-security-operator
      namespace: openshift-operators
    subscription: 
      channel: quay-v3.3
      installPlanApproval: Automatic
      name: container-security-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorGroupNamespaces: 
      - openshift-operators
    createNamespace: false

  - name: namespace-configuration-operator
    metadata:
      operatorName: namespace-configuration-operator
      namespace: namespace-configuration-operator
    subscription: 
      channel: alpha
      installPlanApproval: Automatic
      name: namespace-configuration-operator
      source: community-operators
      sourceNamespace: openshift-marketplace
    operatorGroupNamespaces: 
      - namespace-configuration-operator
    createNamespace: true

  # - name: group-sync-operator
  #   metadata:
  #     operatorName: group-sync-operator
  #     namespace: group-sync-operator
  #   subscription: 
  #     channel: alpha
  #     name: group-sync-operator
  #     source: community-operators
  #     sourceNamespace: openshift-marketplace
  #   operatorGroupNamespaces: 
  #     - group-sync-operator
  #   createNamespace: true

  - name: node-problem-detector
    metadata:
      operatorName: node-problem-detector
      namespace: node-problem-detector
    subscription: 
      channel: alpha
      name: node-problem-detector
      source: community-operators
      sourceNamespace: openshift-marketplace
    operatorGroupNamespaces: 
      - node-problem-detector
    createNamespace: true