#https://docs.newrelic.com/docs/integrations/kubernetes-integration/installation/install-kubernetes-integration-using-helm

newrelic-infrastructure:
  customSecretName: new-relic-license #name of the secret with the license
  customSecretLicenseKey: license-key #key in the secret
  cluster: crc
  config.custom_attributes.cluster: crc
  privileged: true
  rbac.pspEnabled: true
  serviceAccount: 
    create: true
    name: newrelic-infrastructure
  #newrelic-infrastructure.config.proxy: http://10.0.0.1
