#https://docs.newrelic.com/docs/integrations/kubernetes-integration/installation/install-kubernetes-integration-using-helm

newrelic-infrastructure:
  customSecretName: new-relic-license #name of the secret with the license
  customSecretLicenseKey: license-key #key in the secret
  cluster: crc
  config.custom_attributes.cluster: crc
  privileged: true
  rbac.pspEnabled: true
  serviceAccount: 
    create: true
    name: new-relic
  newrelic-infrastructure.config.proxy: http://10.0.0.1

nri-kube-events:
  customSecretName: new-relic-license #name of the secret with the license
  customSecretLicenseKey: license-key #key in the secret
  cluster: crc
  serviceAccount: 
    name: new-relic

kube-state-metrics:
  rbac.pspEnabled: true
  serviceAccount: 
    create: true
    name: kube-state-metrics
