apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: githubidp 
    mappingMethod: claim 
    type: GitHub
    github:
      clientID: {{ .Values.clientID }}
      clientSecret: 
        name: {{ .Values.clientSecretName }}
      # organizations: 
      # - myorganization1
      # - myorganization2
      # teams: 
      # - myorganization1/team-a
      # - myorganization2/team-b