{{- range .Values.instances }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .configMapName }}
  namespace: {{ .namespace }}
binaryData:
  cyan-hat-openshift-container-platform.png: >-
    {{ $.Files.Get $.custom_logo_path | b64enc | indent 4 }}
{{- end }}