{{ range .Values.instances }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .configMapName }}
  namespace: {{ .namespace }}
binaryData:
  cyan-hat-openshift-container-platform.png: {{ .Values.custom_logo }}
{{ end }}
